questions_list = [
    # "Are there any additional qualifications or skills that would be a bonus?",
    "Let's begin with the basics. What's the job title you're hiring for?",
    "Thanks! And is this position full-time, part-time, or contract?",
    "Which department will this role be in?",
    "Got it. And who will this person report to?",
    "Well. Where is this position based at?",
    "Can you talk about the work arrangement for this role? (Hybrid, WFH, In Office, On Field Etc.)",
    "Now, let's talk about the key responsibilities. Can you describe the main duties this person will handle?",
    "Got it! Would you like to add any additional tasks or responsibilities?",
    "Great! What are the specific long-term goals and expectations from this position?",
    "Got it! What is the immediate challenge that a new hire would face in this position?",
    "Great! What defines success in this role?",
    "How does this role align with and support the company's overarching strategic objectives?",
    "How frequently will this individual collaborate with teams from other departments, such as marketing, sales, or customer success?",
    "Who are the key stakeholders this person will regularly interact with outside the immediate team?",
    "Let's cover the skills and qualifications now. What's the minimum years of experience required for this role?",
    "Great! Any specific educational background or certifications needed?",
    "Are there any skills you expect them to develop?",
    "And are there any must-have technical skills or soft skills?",
    "What type of working style thrives for this role?",
    "Are there any additional qualifications or skills that would be a bonus?",
    "Is there any preferred candidate background that would fit the role best?",
    "What opportunities for learning and growth does this role offer?",
    "What benefits will you offer with this role?",
    "What kind of guidance or mentorship can the new hire expect?",
    "How would you describe your management style?",
    "And what's the work culture like on the team?",
]
